### PR TITLE
Inheritance is cool

### PR DESCRIPTION
**Pull request by qiqvo**
Used the Base class to implement inheritance structure. 
Base has a dict `_inside` which has all the fields the Instance will ever need. The list of those names is `fields` and it should be carefully completed.

Method `__get_the` returns raw data after json parsing. 
The Child class uses its own variant which redirects to Base's `__get_the`.

Haven't yet checked a thing. :) 

Now it's easy to add the other classes like Mission.

PS: Functions `search` were not changed or removed. They should be static (if they really should ever be).

### CODE REVIEW

**Comment by veetaw** [comment]
**Thanks** for the pullrequest! I had not thought about this kind of implementation.

Didn't get a thing, can you please post an example usage of the library with this implementation?

Before it was: (random example)
```python
from llpy.agency import Agency

a = Agency()
print(a.agencies)

```


By the way, what do you mean with "_Haven't yet checked a thing. :)_"?

**Comment by qiqvo** [comment]
Haven't yet 'compiled'. 

```
from llpy.agency import Agency

agency_name = 'nasa'
a = Agency(agency_name)
print(a['id'], a['name'])
```

Now `Agency a` won't init (like all the Base-children classes) w/o `agency_name` or sth. I think `Agency` object should not held all the agencies. 
All the needed pieces of info will be saved in a dict in the object. Later you can get them with `[]` operator.

**Comment by veetaw** [comment]
Thanks!!  Sorry for the delay.

I'll test and let you know

**Comment by veetaw** [comment]
it doesn't work or probably I did not get how to use it! :/

Prob I'll move master branch to a new one called "inherritance" and I'll continue the developement of the "old" module

**Pull request merged**
